# Generated by Django 3.2.15 on 2022-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncity', models.CharField(max_length=30)),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=40)),
                ('Mobile', models.CharField(max_length=30)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='igallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=400)),
                ('gpic', models.ImageField(default='', upload_to='static/gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('pcode', models.TextField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=90)),
                ('mob', models.CharField(max_length=30)),
                ('acc', models.CharField(max_length=30)),
                ('caddress', models.TextField()),
                ('paddress', models.TextField()),
                ('ppic', models.ImageField(null=True, upload_to='static/profile/')),
            ],
        ),
        migrations.CreateModel(
            name='myblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=40)),
                ('bdes', models.TextField()),
                ('bpicture', models.ImageField(null=True, upload_to='static/blogs')),
                ('bdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ncategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('cpic', models.ImageField(null=True, upload_to='static/category')),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shead', models.CharField(max_length=300)),
                ('ssubject', models.CharField(max_length=500)),
                ('sdes', models.TextField()),
                ('spic', models.ImageField(default='', upload_to='static/slider/')),
            ],
        ),
    ]
