# Generated by Django 3.2.15 on 2022-09-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncountry', models.CharField(max_length=30)),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='donates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammt', models.TextField(max_length=28)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('mob', models.TextField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=30)),
                ('pcode', models.CharField(max_length=30)),
                ('occn', models.CharField(max_length=100)),
            ],
        ),
    ]
