# Generated by Django 3.2.15 on 2022-09-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_country_donates'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nstate', models.CharField(max_length=30)),
                ('sdate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='donates',
            name='pcode',
            field=models.TextField(max_length=30),
        ),
    ]
