# Generated by Django 3.2.4 on 2022-09-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_vgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='donates',
            name='payss',
            field=models.ImageField(null=True, upload_to='static/payment'),
        ),
    ]
